/**
 * api/_lib/handler.ts — the shared Vercel handler.
 *
 * Every route file under api/ re-exports this. They all delegate to the same
 * dispatcher the local Node server uses, so there is one routing table and the
 * deployed function cannot disagree with `npm start`.
 */
import { handleRequest } from '../../server/sos-server.mjs';
import type { VercelRequest, VercelResponse } from './types.js';

/** Vercel function tuning. Re-declared per route file so it stays statically visible. */
export const serverlessConfig = { maxDuration: 60 } as const;

export function handler(req: VercelRequest, res: VercelResponse): void {
  // A filesystem-matched function route receives the real request URL, so there
  // is nothing to reconstruct. Assert that rather than silently dispatching on
  // the wrong path — a wrong-path 404 looks identical to a routing bug.
  if (!req.url || !req.url.startsWith('/api')) {
    res.status(500).json({
      ok: false,
      error: 'Routing error: the request reached this function without a usable /api path.',
      detail: `req.url was ${JSON.stringify(req.url)}. This means the Vercel route `
            + 'is not matching the way vercel.json and the api/ layout assume. '
            + 'Run `npm run verify:routing`.',
    });
    return;
  }

  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Referrer-Policy', 'no-referrer');

  try {
    handleRequest(req, res);
  } catch (err) {
    // A throw out of the dispatcher would otherwise become an opaque 500 page.
    const message = err instanceof Error ? err.message : 'Unknown error';
    const status = (err as { status?: number })?.status || 500;
    if (!res.headersSent) {
      res.status(status).json({ ok: false, error: message });
    }
  }
}

/**
 * Build a route module that delegates to the shared handler.
 *
 * Used by the generator (scripts/gen-vercel-routes.mjs) so the per-route files
 * are identical apart from their doc comment, and regenerating is idempotent.
 */
export function routeSource(doc: string, depth: number): string {
  const up = depth === 0 ? './_lib/handler.js' : '../_lib/handler.js';
  return `/**
 * ${doc}
 *
 * Generated by scripts/gen-vercel-routes.mjs — edit the generator, not this
 * file. It re-exports the shared handler, which delegates to the same
 * handleRequest() that \`npm start\` uses, so the deployed routes and the local
 * server cannot drift apart.
 */
import { handler } from '${up}';
import type { VercelRequest, VercelResponse } from '${depth === 0 ? './_lib/types.js' : '../_lib/types.js'}';

export const config = { maxDuration: 60 };

export default function route(req: VercelRequest, res: VercelResponse): void {
  handler(req, res);
}
`;
}
