/**
 * Plain-text endpoint listing, kept for scripts that scrape it.
 *
 * Generated by scripts/gen-vercel-routes.mjs — edit the generator, not this
 * file. It re-exports the shared handler, which delegates to the same
 * handleRequest() that `npm start` uses, so the deployed routes and the local
 * server cannot drift apart.
 */
import { handler } from './_lib/handler.js';
import type { VercelRequest, VercelResponse } from './_lib/types.js';

export const config = { maxDuration: 60 };

export default function route(req: VercelRequest, res: VercelResponse): void {
  handler(req, res);
}
